# -*- coding: utf-8 -*-
"""hello-google-colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nt9DiA6rR1mhhlq09_jhPjZ4U3r8lAq9

みなさん、おはこんばんにちございます。  
Syrup Lang Advent Calender 第 2 日目の記事だと思います。

はじめに
===========================================================================

Google Colab を使って Kaggle のタイタニックのコンペ用の Python スクリプトを書きたいなと思ったんですが、Google Colab の使い方を書いていく記事になってしまっていると思います。

まずは ゲームで使う `train.csv` と `test.csv` をアップロードします。

以下のコードを書いて、実行してみましょう。  
わかりやすくするために、ここでは同じコードを 2 つのコードセルに別々に書いて`train.csv` と `test.csv` をアップロードします。
"""

from google.colab import files

uploaded = files.upload()

from google.colab import files

uploaded = files.upload()

"""データの確認
-----------------------------------------------------------------------------------------------------

これで `train.csv` と `test.csv` の 2 つのファイルがアップロードされました。  
この 2 つのファイルを `pandas` で読み込んで、確認してみましょう。
"""

import pandas

train = pandas.read_csv( 'train.csv' )

train.head()

import pandas

test = pandas.read_csv( 'test.csv' )

test.head()

"""Age に穴があるので、それを埋めます。  (何故わかったのかは省略する)  
穴は NaN で表されますが、その部分に Age の中央値を入れることにします。

とりあえず、Age の中央値を確認してみましょう:
"""

import pandas

train = pandas.read_csv( 'train.csv' )

train['Age'].median()

"""28.0 と出ました。  
Age の NaN の部分には 28.0 が入るようです。
"""

import pandas

train = pandas.read_csv( 'train.csv' )

train['Age']      = train['Age'].fillna( train['Age'].median() )

train[[ 'Name', 'Age']].query( 'Age == 28.0' )

"""iPython Notebook で書いたものを Markdown にしているので、実行可能なスクリプトにするために、`import` を書いていてウザさがあるかもしれませんが、我慢してください。

そーいうわけで、`Embarked`  にも NaN があるので、一番多いと思われる(多分) S (サウサンプトン)を入れることにした。
"""

import pandas

train             = pandas.read_csv( 'train.csv' )

train['Embarked'] = train['Embarked'].fillna( 'S' )

train[[ 'Name', 'Embarked']].query( 'Embarked == "S"' )

"""`Sex` は文字列を数値に変換します。

`male` は 0 に、`female` は 1 に変換します。
"""

import pandas

train             = pandas.read_csv( 'train.csv' )

train['Sex']      = train['Sex'].replace( 'male'  , 0 )
train['Sex']      = train['Sex'].replace( 'female', 1 )

train.head()